var config = {
    width: 1040,
    height: 780,
    phyisics: "arcade",
    backgroundColor: 0x000000,
    scene: [PreloadScene, LoadScene, MenuScene, GameScene, VideoScene, ZoomScene, WinScene, TransitionScene, CreditScene, EnvelopeScene, StartScene, CaseScene],
    pixelArt: true,
    audio: {
        disableWebAudio: true
    },
}

var game = new Phaser.Game(config);

var musicVolume = 1;
var sfxVolume = 1;

var lastComplete = 0; // Used to track puzzle state
var lastVideo = 0; // Used to track video state


var NGoptions = {
    version: "1.0.0",
    preloadMedals: true,
}

var appID = "56239:Ig786Yt0";
var aesKey = "ie6zyFmVlkcDHIDQmLRcdA==";

var collaborators = [
    "Alex-PhantomGlitch",
    "AzieOzo",
    "BaldIntegra",
    "BingoWaders",
    "Bleak-Creep",
    "Bozubrain",
    "CaioAdriel2006",
    "CayFettArt",
    "Chanma",
    "CheddarExuberant",
    "ChromaCee",
    "Chuw_Croissantier",
    "CosmicPunked",
    "CrowdDoll",
    "Crumptain",
    "dannydoods",
    "devoidgazer",
    "Ducksen",
    "EalainEP",
    "EddyPaintings",
    "Emmazapan",
    "EpithetSoup",
    "FooxdotPNG",
    "GallowJolt",
    "Healmore6969",
    "homunc",
    "jazhelmet",
    "JSuika",
    "KayEf",
    "KDT",
    "KokoroHatsaru",
    "kubernikus18",
    "Letaug",
    "Limuthrysxx",
    "Lobsteritus",
    "Lolofyr",
    "MaiSanityIsNoMore",
    "Marccelothepinter",
    "MassiveMarioLuigi700",
    "MysteryMintt",
    "NeoBioHazardus",
    "NeverSkipEggDay",
    "NoodleDood12",
    "Phaox05",
    "Picochu",
    "RGB-TAT0",
    "ryve",
    "Saminat",
    "Schreckengast",
    "Senranx",
    "Sevi",
    "SloppyStinko",
    "SuperJeffoMan",
    "TechnoCookie",
    "TheADHX",
    "TheExtreamH",
    "ThePikaGlass",
    "TingSing",
    "Trannenspiel",
    "Tyangerine",
    "Urichov",
    "wild0moon",
    "YuloYuppy",
    "z1z0",
    "ZaazNG",
    "bonus1",
    "bonus2",
    "bonus3",
    "bonus4",
    "bonus5",
    "bonus6"];

var artnames = [
    "Art",
    "Art",
    "ENAPOCALYPSE",
    "Lopz, Blue & Sinny",
    "Static Prison",
    "Art",
    "Statue of Pico",
    "Art",
    "the 'pico' pose",
    "Shrimpmen B]",
    "A Match Made in Philly",
    "Like father, like son",
    "Edgelordettes ",
    "Art",
    "Britain's Fifth Most Beloved Illusionist",
    "Let's Play!",
    "Another Castle Crasher Casualty",
    "Art",
    "Art",
    "you walked into the wrong gay bar",
    "Art",
    "Have Some Ear Candy",
    "Art",
    "Dr. Fetus takes a nice walk in the forest",
    "Margo featuring a cameo from ula",
    "Art",
    "Art",
    "Funki Funki Night",
    "Art",
    "Art",
    "Thunder Warrior Red Knight",
    "Art",
    "Cute and Deadly",
    "Death of tarboy",
    "Art",
    "You Gotta Run",
    "Get Gang Banged",
    "Hope your mom gets better mizu",
    "Lock and loaded Gorillia - Chaos Faction",
    "ENA",
    "Art",
    "The Gift",
    "Art",
    "Bitey of Brackenwood",
    "The Binding of Newgrounds",
    "Art",
    "Ritz Chilling under the Big Cheese Moon in the Sky",
    "Pico's Present Redux",
    "In the Ocean Blue",
    "Art",
    "Tower of Heaven",
    "Trick Or Treat, Smack Your Sleet",
    "Art",
    "i could probably make a joke about Art stress or something",
    "Orla and her worm in a ng store buying something or someshit. I don't know.",
    "Newgrounds Rumble Racing",
    "Art",
    "The Problems of the Future, Today!",
    "There she is",
    "Cute Girlies",
    "Just got back from whispering my darkest secret to the nut",
    "Art",
    "Starry Blues",
    "it goes with a the",
    "Art",
    "Art",
    "Art",
    "NOX",
    "Ritz Roll",
    "Art",
    "Art",
];